//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<System.DateTime> ForgotPasswordDate { get; set; }
        public Nullable<System.DateTime> ChangePasswordDate { get; set; }
        public string OldFirstName { get; set; }
        public string OldLastName { get; set; }
        public string OldContactNumber { get; set; }
        public string OldAddress { get; set; }
        public Nullable<System.DateTime> ChangeBasicInfoDate { get; set; }
    }
}
