//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public string Email { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Subtotal { get; set; }
        public byte[] CartImage { get; set; }
    }
}
