//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartBuilder
    {
        public int CartBuilderId { get; set; }
        public string Email { get; set; }
        public Nullable<int> BuilderId { get; set; }
        public string BuilderName { get; set; }
        public Nullable<int> BuilderPrice { get; set; }
        public Nullable<int> QuantityBuilder { get; set; }
        public Nullable<int> SubtotalBuilder { get; set; }
        public byte[] BuilderImage { get; set; }
    }
}
