//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedOrders
    {
        public int CompletedId { get; set; }
        public string OrderName { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<int> OrderPrice { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string PaymentMode { get; set; }
        public string CustomerAccountNumber { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    }
}
