//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public int CustomerAccountId { get; set; }
        public int CustomerId { get; set; }
        public int TransactionId { get; set; }
        public System.DateTime LastPurchaseDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
