//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1FinalCapstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInformation
    {
        public int OrderInformationId { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public int ShippingId { get; set; }
        public int PriceOrderInfo { get; set; }
        public int QuantityOrderInfo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product2 Product2 { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
